#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : how_to_pyac3airborne  # The title of the book. Will be placed in the left navbar.
author                      : pyac3airborne community  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
# bib file
bibtex_bibfiles:
    - references.bib
bibtex_reference_style: 
    - author_year
execute:
  timeout: 120


# configuration for Binder
# Information about where the book exists on the web
repository:
  url                       : https://github.com/igmk/how_to_pyac3airborne  # Online location of the book
  path_to_book              : how_to_pyac3airborne/  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
